FROM node:18.14.0 as deps
WORKDIR /app


COPY ./back/package.json ./back/yarn.lock ./
COPY ./back/prisma ./prisma
COPY ./shared ./shared

RUN sed -i -e 's/:..\/shared/:\/app\/shared/g' package.json

RUN yarn install


FROM node:18.14.0
WORKDIR /app
EXPOSE 3000

COPY --from=deps /app/node_modules ./node_modules

COPY ./back .

CMD ["yarn", "dev:docker"]