version: "3.7"

services:
  db:
    image: postgres:12.2-alpine
    container_name: matchmaking-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - matchmaking-vol:/var/lib/postgresql/data
      - ../init-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
    ports:
      - "11000:5432"
  app:
    build:
      context: ..
      dockerfile: Dockerfile.prod
    container_name: uis-app
    restart: always
    ports:
      - "8080:${PORT}"
    environment:
      PORT: ${PORT}
      JWT_SECRET: ${JWT_SECRET}
      DATABASE_URL: ${DATABASE_URL}

volumes:
  matchmaking-vol: