FROM node:18.14.0 as deps
WORKDIR /app

COPY package.json yarn.lock ./
COPY prisma ./prisma

RUN yarn install --frozen-lockfile

FROM node:18.14.0
WORKDIR /app
EXPOSE 3000

COPY package.json yarn.lock ./

COPY --from=deps /app/node_modules ./node_modules
COPY . .

CMD ["yarn", "dev:docker"]