FROM node:16.17-alpine3.16 as deps

WORKDIR /app

COPY package.json yarn.lock ./
COPY prisma ./prisma

RUN yarn global add typescript

RUN yarn install --production --frozen-lockfile \
    && yarn build \
    && npx prisma generate \
    && yarn cache clean


COPY . .

## this is stage two , where the app actually runs

FROM node:16-alpine as runner

EXPOSE 3000
WORKDIR /app

COPY --from=deps /app/node_modules ./node_modules
COPY --from=deps /app/dist ./dist

CMD ["yarn", "start"]